### ISSUE TITLE
Responses of requested comments cannot be opened

### ISSUE THREAD

**Issue by Gravatronics** [WoltLab/WCF#2399]
If a specific comment is requested due to a commentID in the URL (`…/#comment1`) and if that comment is not shown on the page anyway, the comment is loaded dynamically and inserted on the page above the field to create a new comment.

1. No responses of the comment are shown.
2. When clicking on `X more replies` to show the responses, an exception is thrown:

```
The parameter “lastResponseTime” is missing or invalid.

Stacktrace:
#0 /wsc31/lib/data/AbstractDatabaseObjectAction.class.php(431): wcf\data\AbstractDatabaseObjectAction->readValue('lastResponseTim...', false, 'data', 1, 1)
#1 /wsc31/lib/data/comment/response/CommentResponseAction.class.php(146): wcf\data\AbstractDatabaseObjectAction->readInteger('lastResponseTim...', false, 'data')
#2 [internal function]: wcf\data\comment\response\CommentResponseAction->validateLoadResponses(Array)
#3 /wsc31/lib/data/AbstractDatabaseObjectAction.class.php(189): call_user_func_array(Array, Array)
#4 /wsc31/lib/action/AJAXProxyAction.class.php(71): wcf\data\AbstractDatabaseObjectAction->validateAction()
#5 /wsc31/lib/action/AJAXInvokeAction.class.php(104): wcf\action\AJAXProxyAction->invoke()
#6 /wsc31/lib/action/AbstractAction.class.php(47): wcf\action\AJAXInvokeAction->execute()
#7 /wsc31/lib/action/AJAXInvokeAction.class.php(63): wcf\action\AbstractAction->__run()
#8 /wsc31/lib/system/request/Request.class.php(83): wcf\action\AJAXInvokeAction->__run()
#9 /wsc31/lib/system/request/RequestHandler.class.php(96): wcf\system\request\Request->execute()
#10 /wsc31/index.php(9): wcf\system\request\RequestHandler->handle('wcf')
#11 {main}
```

This issue is potentially caused by the same underlying problem as https://github.com/WoltLab/WCF/issues/2391.

**Comment by dtdesign** [comment]
Issue was caused by #2391
