### ISSUE TITLE
JavaScript breaks without debug mode

### ISSUE THREAD

**Issue by KittMedia** [WoltLab/WCF#3469]
Currently, as soon as the debug mode is getting disabled, the JavaScript in the frontend doesn’t work anymore.

Error message:
```
ReferenceError: Can't find variable: COMPILER_TARGET_DEFAULT
```
(following errors ignored)

**Comment by dtdesign** [comment]
I was not able to reproduce this locally, can you please include the stacktrace and the name of the file? In addition, please provide which exact version you have tested this with.

**Comment by KittMedia** [comment]
Oh yes, of course:
```
[Error] ReferenceError: Can't find variable: COMPILER_TARGET_DEFAULT
	Globaler Code (WCF.Combined.min.js:1:341215)
```
By inspecting this line the result is this:
https://github.com/WoltLab/WCF/blob/db8a92cc7821795a1a62e52be26bed9c294afc0c/wcfsetup/install/files/js/WCF.js#L962

I built upon the latest master commit from today, db8a92c.

**Comment by dtdesign** [comment]
I am unable to reproduce this and frankly it doesn't even make sense, because that variable is removed (*) at compile time. The phrase `COMPILER_TARGET_DEFAULT` is not to be found anywhere in the `WCF.Combined.min.js` file, so possibly you are dealing with corrupted files?

In the end, please do not expect the non debug mode to be functional in the master branch at any given time, we usually do not run the compiler process for non release builds.

(*) Defined as a constant boolean value depending on the output type.

**Comment by KittMedia** [comment]
> so possibly you are dealing with corrupted files?

That seems to be the issue, then. I use to compile the files by myself instead of relying on the `WCF.Combined.min.js` since I think they weren’t available all the time. Can you share your JavaScript compiling settings so that I can setup them accordingly?

**Comment by dtdesign** [comment]
> Can you share your JavaScript compiling settings so that I can setup them accordingly?

Yes! You can invoke this command from within the repository to compile the files:
```
node extra/_buildCore.js
```

If you would like to compile the scripts in a different repository:
```
node extra/_buildExternal.js ../path/to/target/
```

**Comment by KittMedia** [comment]
Thank you, I will have a look on it.

**Comment by KittMedia** [comment]
Unfortunately, I can’t get it working. I used the following commands:
```
WCF5.3/extra$ npm install
npm WARN extra No description
npm WARN extra No repository field.
npm WARN extra No license field.

added 15 packages from 88 contributors and audited 15 packages in 1.846s
found 0 vulnerabilities
```

```
WCF5.3/extra$ node _buildCore.js
WCF.Combined.min.js: 47.194ms
WCF.Combined.tiny.min.js: 13.302ms
redactor.combined.min.js: 65.991ms
/bin/sh: 1: r.js: not found
child_process.js:655
    throw err;
    ^

Error: Command failed: r.js -o require.build.js uglify2.compress.global_defs.COMPILER_TARGET_DEFAULT=true
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at /home/gitlab-runner/temp/WCF5.3/extra/_buildCore.js:92:22
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/gitlab-runner/temp/WCF5.3/extra/_buildCore.js:84:19)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  status: 127,
  signal: null,
  output: [ null, null, null ],
  pid: 7673,
  stdout: null,
  stderr: null
}
```

If I use the exact command mentioned above from outside the `extra` directory, the error message is the following:
```
WCF5.3$ node extra/_buildCore.js
internal/bootstrap/switches/does_own_process_state.js:115
  rawMethods.chdir(directory);
             ^

Error: ENOENT: no such file or directory, chdir '/home/gitlab-runner/temp/WCF5.3' -> '../wcfsetup/install/files/js/'
    at process.wrappedChdir [as chdir] (internal/bootstrap/switches/does_own_process_state.js:115:14)
    at Object.<anonymous> (/home/gitlab-runner/temp/WCF5.3/extra/_buildCore.js:29:9)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'chdir',
  path: '/home/gitlab-runner/temp/WCF5.3',
  dest: '../wcfsetup/install/files/js/'
}
```

Any advice, @dtdesign?

**Comment by TimWolla** [comment]
> /bin/sh: 1: r.js: not found

It appears you'll manually need to download [require.js optimizer](https://requirejs.org/docs/optimization.html) into `files/js/`. I believe the script can also be adjusted to use `node_modules/.bin/r_js` instead of `r.js`.

**Comment by KittMedia** [comment]
I updated the line to `const rjsCmd = (process.platform === "win32") ? "r.js.cmd" : "../../../../extra/node_modules/.bin/r_js"`. This seems to be working but now the following error occurs:
```
WCF.Combined.min.js: 38.958ms
WCF.Combined.tiny.min.js: 12.114ms
redactor.combined.min.js: 104.572ms

Tracing dependencies for: WoltLabSuite/_Meta
Cannot optimize network URL, skipping: https://connect.facebook.net/en_US/sdk.js
Cannot optimize network URL, skipping: https://platform.twitter.com/widgets.js
Error: Parse error using esprima for file: /home/gitlab-runner/temp/WCF5.3/wcfsetup/install/files/js/3rdParty/zxcvbn.js
Error: Line 5: Unexpected token ...
In module tree:
    WoltLabSuite/_Meta
      WoltLabSuite/Core/Ui/User/PasswordStrength

Error: Error: Parse error using esprima for file: /home/gitlab-runner/temp/WCF5.3/wcfsetup/install/files/js/3rdParty/zxcvbn.js
Error: Line 5: Unexpected token ...
In module tree:
    WoltLabSuite/_Meta
      WoltLabSuite/Core/Ui/User/PasswordStrength

    at /home/gitlab-runner/temp/WCF5.3/extra/node_modules/requirejs/bin/r.js:27695:47

child_process.js:655
    throw err;
    ^

Error: Command failed: ../../../../extra/node_modules/.bin/r_js -o require.build.js uglify2.compress.global_defs.COMPILER_TARGET_DEFAULT=true
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at /home/gitlab-runner/temp/WCF5.3/extra/_buildCore.js:92:22
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/gitlab-runner/temp/WCF5.3/extra/_buildCore.js:84:19)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 23864,
  stdout: null,
  stderr: null
}
```

**Comment by KittMedia** [comment]
After fixing this, after uglifying WoltLabSuite.Core.tiny.min.js, the following error occurs:
```
WoltLabSuite.Core.tiny.min.js: 5.320s
internal/fs/utils.js:701
    throw new ERR_INVALID_ARG_TYPE(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFileSync (fs.js:1409:5)
    at /home/gitlab-runner/temp/WCF5.3/extra/_buildCore.js:122:16
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/gitlab-runner/temp/WCF5.3/extra/_buildCore.js:118:6)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

nodejs is v14.8.0.

**Comment by TimWolla** [comment]
@KittMedia I moved this into #3520 to keep things nice and tidy.
