### ISSUE TITLE
Creating the JavaScript bundles fails for master

### ISSUE THREAD

**Issue by TimWolla** [WoltLab/WCF#3520]
After fixing this, after uglifying WoltLabSuite.Core.tiny.min.js, the following error occurs:
```
WoltLabSuite.Core.tiny.min.js: 5.320s
internal/fs/utils.js:701
    throw new ERR_INVALID_ARG_TYPE(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFileSync (fs.js:1409:5)
    at /home/gitlab-runner/temp/WCF5.3/extra/_buildCore.js:122:16
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/gitlab-runner/temp/WCF5.3/extra/_buildCore.js:118:6)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

nodejs is v14.8.0.

_Originally posted by @KittMedia in https://github.com/WoltLab/WCF/issues/3469#issuecomment-675002340_

**Comment by dtdesign** [comment]
Note: This looks like an incompatibility with newer node.js or uglifyjs versions, I'm still using node.js 10 LTS to run it.

**Comment by TimWolla** [comment]
> This looks like an incompatibility with newer node.js

This one. It works for node 12, breaks on node 14.
