### ISSUE TITLE
Devtools scan the project multiple times in devtools-project-sync

### ISSUE THREAD

**Issue by TimWolla** [WoltLab/WCF#3961]
```
Exception in /var/www/html/lib/system/devtools/package/DevtoolsPackageArchive.class.php:49
Stack trace:
#0 /var/www/html/lib/data/devtools/project/DevtoolsProject.class.php(129): wcf\system\devtools\package\DevtoolsPackageArchive->openArchive()
#1 /var/www/html/lib/data/devtools/project/DevtoolsProject.class.php(91): wcf\data\devtools\project\DevtoolsProject->validatePackageXml()
#2 /var/www/html/acp/templates/compiled/0_wcf_2_devtoolsProjectSync.php(678): wcf\data\devtools\project\DevtoolsProject->validate()
#3 /var/www/html/lib/system/template/TemplateEngine.class.php(346): include('/var/www/html/a...')
#4 /var/www/html/lib/page/AbstractPage.class.php(339): wcf\system\template\TemplateEngine->display('devtoolsProject...', 'wcf')
#5 /var/www/html/lib/page/AbstractPage.class.php(120): wcf\page\AbstractPage->show()
#6 /var/www/html/lib/system/request/Request.class.php(89): wcf\page\AbstractPage->__run()
#7 /var/www/html/lib/system/request/RequestHandler.class.php(119): wcf\system\request\Request->execute()
#8 /var/www/html/acp/index.php(11): wcf\system\request\RequestHandler->handle('wcf', true)
#9 {main}
```

```
Exception in /var/www/html/lib/system/devtools/package/DevtoolsPackageArchive.class.php:49
Stack trace:
#0 /var/www/html/lib/data/devtools/project/DevtoolsProject.class.php(129): wcf\system\devtools\package\DevtoolsPackageArchive->openArchive()
#1 /var/www/html/lib/data/devtools/project/DevtoolsProject.class.php(91): wcf\data\devtools\project\DevtoolsProject->validatePackageXml()
#2 /var/www/html/acp/templates/compiled/0_wcf_2_devtoolsProjectSync.php(706): wcf\data\devtools\project\DevtoolsProject->validate()
#3 /var/www/html/lib/system/template/TemplateEngine.class.php(346): include('/var/www/html/a...')
#4 /var/www/html/lib/page/AbstractPage.class.php(339): wcf\system\template\TemplateEngine->display('devtoolsProject...', 'wcf')
#5 /var/www/html/lib/page/AbstractPage.class.php(120): wcf\page\AbstractPage->show()
#6 /var/www/html/lib/system/request/Request.class.php(89): wcf\page\AbstractPage->__run()
#7 /var/www/html/lib/system/request/RequestHandler.class.php(119): wcf\system\request\Request->execute()
#8 /var/www/html/acp/index.php(11): wcf\system\request\RequestHandler->handle('wcf', true)
#9 {main}
```

This is inefficient. The opened archive should probably be cached in `DevtoolsProject`.

**Comment by TimWolla** [comment]
Related to: #3830
