### ISSUE TITLE
6.1: User-Popover broken

### ISSUE THREAD

**Issue by mutec** [WoltLab/WCF#5887]
when hovering the username of myself when viewing a user profile:
```
Fehlermeldung
Could not map type 'array{id: positive-int}'.


Exception:
CuyZ\Valinor\Mapper\TypeTreeMapperError: Could not map type `array{id: positive-int}`. An error occurred at path id: Value 'NaN' is not a valid positive integer. in /lib/system/api/cuyz/valinor/src/Mapper/TypeTreeMapper.php:28
Stack trace:
#0 /lib/http/Helper.class.php(119): CuyZ\Valinor\Mapper\TypeTreeMapper->map()
#1 /lib/action/UserPopoverAction.class.php(29): wcf\http\Helper::mapQueryParameters()
#2 /lib/system/request/Request.class.php(48): wcf\action\UserPopoverAction->handle()
#3 /lib/http/middleware/HandleValinorMappingErrors.class.php(35): wcf\system\request\Request->handle()
#4 /lib/http/RequestHandlerMiddleware.class.php(37): wcf\http\middleware\HandleValinorMappingErrors->process()
#5 /lib/http/middleware/HandleExceptions.class.php(36): wcf\http\RequestHandlerMiddleware->handle()
#6 /lib/http/RequestHandlerMiddleware.class.php(37): wcf\http\middleware\HandleExceptions->process()
#7 /lib/http/middleware/TriggerBackgroundQueue.class.php(43): wcf\http\RequestHandlerMiddleware->handle()
#8 /lib/http/RequestHandlerMiddleware.class.php(37): wcf\http\middleware\TriggerBackgroundQueue->process()
#9 /lib/http/middleware/JsonBody.class.php(49): wcf\http\RequestHandlerMiddleware->handle()
#10 /lib/http/RequestHandlerMiddleware.class.php(37): wcf\http\middleware\JsonBody->process()
#11 /lib/http/middleware/CheckForMultifactorRequirement.class.php(46): wcf\http\RequestHandlerMiddleware->handle()
#12 /lib/http/RequestHandlerMiddleware.class.php(37): wcf\http\middleware\CheckForMultifactorRequirement->process()
#13 /lib/http/middleware/CheckForForceLogin.class.php(61): wcf\http\RequestHandlerMiddleware->handle()
#14 /lib/http/RequestHandlerMiddleware.class.php(37): wcf\http\middleware\CheckForForceLogin->process()
#15 /lib/http/middleware/CheckForOfflineMode.class.php(33): wcf\http\RequestHandlerMiddleware->handle()
#16 /lib/http/RequestHandlerMiddleware.class.php(37): wcf\http\middleware\CheckForOfflineMode->process()
#17 /lib/http/middleware/CheckForExpiredAppEvaluation.class.php(63): wcf\http\RequestHandlerMiddleware->handle()
#18 /lib/http/RequestHandlerMiddleware.class.php(37): wcf\http\middleware\CheckForExpiredAppEvaluation->process()
#19 /lib/http/middleware/CheckForEnterpriseNonOwnerAccess.class.php(40): wcf\http\RequestHandlerMiddleware->handle()
#20 /lib/http/RequestHandlerMiddleware.class.php(37): wcf\http\middleware\CheckForEnterpriseNonOwnerAccess->process()
#21 /lib/http/middleware/EnforceAcpAuthentication.class.php(52): wcf\http\RequestHandlerMiddleware->handle()
#22 /lib/http/RequestHandlerMiddleware.class.php(37): wcf\http\middleware\EnforceAcpAuthentication->process()
#23 /lib/http/middleware/CheckUserBan.class.php(45): wcf\http\RequestHandlerMiddleware->handle()
#24 /lib/http/RequestHandlerMiddleware.class.php(37): wcf\http\middleware\CheckUserBan->process()
#25 /lib/http/middleware/CheckSystemEnvironment.class.php(41): wcf\http\RequestHandlerMiddleware->handle()
#26 /lib/http/RequestHandlerMiddleware.class.php(37): wcf\http\middleware\CheckSystemEnvironment->process()
#27 /lib/http/middleware/Xsrf.class.php(66): wcf\http\RequestHandlerMiddleware->handle()
#28 /lib/http/RequestHandlerMiddleware.class.php(37): wcf\http\middleware\Xsrf->process()
#29 /lib/http/middleware/CheckHttpMethod.class.php(42): wcf\http\RequestHandlerMiddleware->handle()
#30 /lib/http/RequestHandlerMiddleware.class.php(37): wcf\http\middleware\CheckHttpMethod->process()
#31 /lib/http/middleware/VaryAcceptLanguage.class.php(45): wcf\http\RequestHandlerMiddleware->handle()
#32 /lib/http/RequestHandlerMiddleware.class.php(37): wcf\http\middleware\VaryAcceptLanguage->process()
#33 /lib/http/middleware/EnforceFrameOptions.class.php(32): wcf\http\RequestHandlerMiddleware->handle()
#34 /lib/http/RequestHandlerMiddleware.class.php(37): wcf\http\middleware\EnforceFrameOptions->process()
#35 /lib/http/middleware/EnforceNoCacheForTemporaryRedirects.class.php(36): wcf\http\RequestHandlerMiddleware->handle()
#36 /lib/http/RequestHandlerMiddleware.class.php(37): wcf\http\middleware\EnforceNoCacheForTemporaryRedirects->process()
#37 /lib/http/middleware/EnforceCacheControlPrivate.class.php(27): wcf\http\RequestHandlerMiddleware->handle()
#38 /lib/http/RequestHandlerMiddleware.class.php(37): wcf\http\middleware\EnforceCacheControlPrivate->process()
#39 /lib/http/middleware/AddAcpSecurityHeaders.class.php(28): wcf\http\RequestHandlerMiddleware->handle()
#40 /lib/http/RequestHandlerMiddleware.class.php(37): wcf\http\middleware\AddAcpSecurityHeaders->process()
#41 /lib/http/middleware/PreventMimeSniffing.class.php(32): wcf\http\RequestHandlerMiddleware->handle()
#42 /lib/http/RequestHandlerMiddleware.class.php(37): wcf\http\middleware\PreventMimeSniffing->process()
#43 /lib/http/middleware/HandleStartupErrors.class.php(32): wcf\http\RequestHandlerMiddleware->handle()
#44 /lib/http/RequestHandlerMiddleware.class.php(37): wcf\http\middleware\HandleStartupErrors->process()
#45 /lib/http/Pipeline.class.php(45): wcf\http\RequestHandlerMiddleware->handle()
#46 /lib/system/request/RequestHandler.class.php(156): wcf\http\Pipeline->process()
#47 /index.php(10): wcf\system\request\RequestHandler->handle()
#48 {main}
```

**Comment by dtdesign** [comment]
I can’t reproduce this issue and it’s not entirely clear what part you are hovering when the error is raised. The passed value `NaN` is an indicator that there is a malformed element that lacks the proper data attribute for the id.

Can you please point out exactly which element causes that error?

**Comment by mutec** [comment]
Hi there,

I just highlighted the exact link (my own profile, logged in, loaded the page twice):
![image](https://github.com/WoltLab/WCF/assets/1749344/fb4bf48c-dae9-4bdd-9fdd-8a1e0113792a)

The source of the element:
`<li>Benutzerprofil von <a href="https://example.com/user/1-dev/" class="userLink" data-user-id="1">dev</a></li>`

The triggered request is sent as GET to `https://example.com/user-popover/?id=NaN`

I assume it`s related to this line since it tries to read `data-object-id`, but there is `data-user-id` given only:
https://github.com/WoltLab/WCF/blob/1dd23e035a1a7fb97e908f6ebdcc662a23d6151d/ts/WoltLabSuite/Core/Component/Popover.ts#L113
